# Generated by Django 4.2.3 on 2023-08-07 10:01

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InputType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_key", models.UUIDField()),
                ("placeholder", models.CharField(max_length=200, null=True)),
                ("required", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "input_type",
                "ordering": ["create_at"],
            },
        ),
        migrations.CreateModel(
            name="SelectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_key", models.UUIDField()),
                ("multiselect", models.BooleanField(default=False)),
                ("required", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "selection_type",
                "ordering": ["create_at"],
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("is_collecting", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "questionnaire",
                "ordering": ["create_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=300)),
                (
                    "key",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ]
                    ),
                ),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="questionnaire.questionnaire",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question",
                "ordering": ["questionnaire"],
            },
        ),
        migrations.CreateModel(
            name="OptionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=300)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selection_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questionnaire.selecttype",
                    ),
                ),
            ],
            options={
                "db_table": "option_value",
                "ordering": ["selection_type"],
            },
        ),
        migrations.AddIndex(
            model_name="questionnaire",
            index=models.Index(fields=["slug"], name="slug_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["questionnaire"], name="questionnaire_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionvalue",
            index=models.Index(
                fields=["selection_type"], name="selection_type_idx"
            ),
        ),
    ]
