# Generated by Django 4.2.3 on 2023-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0002_alter_optionvalue_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["questionnaire", "sequence"]},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["sequence"], name="sequence_idx"),
        ),
    ]
