# Generated by Django 4.2.3 on 2023-08-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0003_alter_question_options_question_sequence_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="tag",
            field=models.CharField(default="DEFAULT", max_length=160),
        ),
        migrations.AddIndex(
            model_name="questionnaire",
            index=models.Index(fields=["tag"], name="tag_idx"),
        ),
    ]
