# Generated by Django 4.2.3 on 2023-08-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0004_questionnaire_tag_questionnaire_tag_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="thumb",
            field=models.URLField(blank=True, null=True),
        ),
    ]
