# Generated by Django 4.2.3 on 2023-08-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0005_questionnaire_thumb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputtype",
            name="placeholder",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
