# Generated by Django 4.2.3 on 2023-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0009_remove_questionnaire_tag_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="label",
            field=models.CharField(max_length=1000),
        ),
    ]
