# Generated by Django 4.2.3 on 2023-09-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0010_alter_question_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnaire",
            options={"ordering": ["-create_at"]},
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
