# Generated by Django 4.2.3 on 2023-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0012_alter_questionnaire_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=300, unique=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
    ]
