# Generated by Django 4.2.3 on 2023-09-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0015_questionnaire_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="downloads",
            field=models.IntegerField(default=0),
        ),
    ]
