# Generated by Django 4.2.3 on 2023-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0017_statistics"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="statistics",
            index=models.Index(fields=["create_at"], name="create_at_idx"),
        ),
    ]
