# Generated by Django 4.2.3 on 2023-09-19 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0018_statistics_create_at_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statistics",
            options={"ordering": ["questionnaire", "create_at"]},
        ),
    ]
