# Generated by Django 4.2.3 on 2023-09-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0020_alter_statistics_create_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inputtype",
            index=models.Index(
                fields=["question_key"], name="question_key_inputType_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="selecttype",
            index=models.Index(
                fields=["question_key"], name="question_key_selectType_idx"
            ),
        ),
    ]
