# Generated by Django 4.2.3 on 2023-09-22 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "questionnaire",
            "0021_inputtype_question_key_inputtype_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="likers",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
