# Generated by Django 4.2.3 on 2023-09-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0022_questionnaire_likers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="thumb",
            field=models.URLField(
                blank=True,
                default="https://firebasestorage.googleapis.com/v0/b/gokag-19eac.appspot.com/o/defaultQuestionnaire.jpg?alt=media",
                null=True,
            ),
        ),
    ]
