# Generated by Django 4.2.3 on 2023-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="refresh_tokens",
        ),
        migrations.AddField(
            model_name="user",
            name="verify_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
