# Generated by Django 4.2.3 on 2023-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0004_remove_user_refresh_tokens_user_verify_token",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verify_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
