# Generated by Django 4.2.3 on 2023-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_user_verify_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verify_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
