# Generated by Django 4.2.3 on 2023-08-07 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_alter_user_verify_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verify_token",
        ),
    ]
