# Generated by Django 4.2.3 on 2023-09-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_remove_user_verify_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                blank=True,
                default="https://thumbs.dreamstime.com/b/untitled-213585789.jpg",
                null=True,
            ),
        ),
    ]
